name: schedule
description: Flutter course schedule

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  fluro: ^2.0.3
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.0+2
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
